### ISSUE TITLE
希望发布Mac系统下的弹幕姬

### ISSUE THREAD

**Issue by redniktony** [copyliu/bililive_dm#1]
B站弹幕姬作者你好！
随着B站直播间的日益壮大，Mac版的弹幕姬也需要更新发布一下啦o(^_^)o。
我作为一个重度的Mac用户，没有弹幕姬我感到很不舒服，每次都要打开直播间才能够看弹幕。相当蛋疼。。。
若您有能力的话～顺便可以推出Linux下弹幕姬吗。
真的是万分感谢！
Tony

**Comment by copyliu** [comment]
我靠你居然在這裡發issue...

**Comment by redniktony** [comment]
………难道不行么，不好意思啊。

**Comment by copyliu** [comment]
没有不行 只是惊讶有人找到这里而已

On Wed, Jul 8, 2015 at 11:11 AM, redniktony <notifications@github.com>
wrote:

> ………难道不行么，不好意思啊。
> On Jul 7, 2015 5:41 PM, "copyliu" <notifications@github.com> wrote:
>
> > 我靠你居然在這裡發issue...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/copyliu/bililive_dm/issues/1#issuecomment-119139015>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/copyliu/bililive_dm/issues/1#issuecomment-119407512>.
>



-- 
<Firefox> 我支持 我喜欢 我信赖
My GPG public key : 0xB186FF6D

**Comment by redniktony** [comment]
嘛还是有人能够找到的嘛。虽然墙高

**Comment by OctavianLee** [comment]
你好，我在做一个开源的弹幕姬，我请求的api是/ajax/msg，我想知道b站是用哪个api请求获得所有弹幕信息的？

**Comment by Asnxthaony** [comment]
前来围观~

**Comment by OctavianLee** [comment]
@redniktony 那个有兴趣 可以改https://github.com/OctavianLee/Barrage，现在还是命令行版的，python做的应该可以使用

**Comment by redniktony** [comment]
十分感谢！

**Comment by liuz430524** [comment]
@redniktony 我是来打广告的 http://pan.baidu.com/s/1qXvWryW

**Comment by AlfnXd** [comment]
> @AlfnXd 你发的就是pandaGao写的吗？

@gMan1990 这是我自己写的，我不认识 pandaGao

**Comment by AlfnXd** [comment]
@gMan1990 不是，这个是我写的，不是他那个
