### ISSUE TITLE
没有办法在别的屏幕侧栏显示弹幕吗

### ISSUE THREAD

**Issue by fr1g** [copyliu/bililive_dm#100]
找了一圈 尝试改坐标解决 然后发现那个侧栏变好大一个杵在主屏幕正中间。
同时建议提供侧栏样式的更多选择
~（甚至是控制台风格）~
另：
系统版本 win11 22000.556
主屏幕1920x1080，副屏1920x1280（很小一个）
当然可以考虑题词板放在副屏显示 但是太单调了！
而且副屏 是放obs的（安详）

**Comment by copyliu** [comment]
可以通過設置偏移量拉過去其他副屏, 拉桿不夠長就手輸數字(

**Comment by copyliu** [comment]
拉杆不够长可以手输数字

**Comment by fr1g** [comment]
记不清当时的情况了。放假回去试试…我记得我拉拉杆时候眼睁睁看着它从右边消失然后从左边冒出来（悲

（假如可以直接拖然后锁定（🍑
