### ISSUE TITLE
每次更新都會丟失設置參數

### ISSUE THREAD

**Issue by akiirui** [copyliu/bililive_dm#115]
設置標籤頁的所有參數都會被重置。
每一次更新後都需要重新設置XY偏移，窗口寬度之類的選項。

**Comment by 1265578519** [comment]
+1

**Comment by copyliu** [comment]
需要研究, 可能考虑把配置文件移到我的文档里

**Comment by copyliu** [comment]
fixed by https://github.com/copyliu/bililive_dm/commit/27e9e93b5b2b9d3ed08c6cdb948031a1d5d83572
released
