### ISSUE TITLE
请问如何打开弹幕姬之后自动加载插件呢？

### ISSUE THREAD

**Issue by xiaocainiao2020** [copyliu/bililive_dm#122]
下载了任务栏助手的插件，方便将弹幕姬隐藏到通知区域。但是每次关闭弹幕姬重新开启的时候，插件就关闭了，还要手动去插件页面开启插件，请问有什么办法能解决这个问题吗，让它打开弹幕姬后就自动加载开启。

**Comment by copyliu** [comment]
插件作者可以自行讓插件自行開啟, 但是我特意叮囑過不建議插件作者這麼弄
