### ISSUE TITLE
无法安装、更新弹幕姬

### ISSUE THREAD

**Issue by zhangkai2001** [copyliu/bililive_dm#123]
如图
![image](https://user-images.githubusercontent.com/72913045/214546199-d31570ea-5dc2-42ff-b6f8-86a37749ab36.png)
系统版本如下
![image](https://user-images.githubusercontent.com/72913045/214546422-9d55ddd9-34dd-4ba2-8d4e-94b8a9d45b70.png)

**Comment by copyliu** [comment]
刪去
HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT\.NETFramework\Security\TrustManager\PromptingLevel
試試

這個目錄默認不存在

**Comment by zhangkai2001** [comment]
抱歉我今天才看到邮件，之前在忙着找工作，删除以后就可以了，感谢您的帮助

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送


发件人: copyliu ***@***.***>
发送时间: Thursday, January 26, 2023 11:34:13 AM
收件人: copyliu/bililive_dm ***@***.***>
抄送: zhangkai2001 ***@***.***>; Author ***@***.***>
主题: Re: [copyliu/bililive_dm] 无法安装、更新弹幕姬 (Issue #123)


h去
HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT.NETFramework\Security\TrustManager\PromptingLevel


@目默J不存在

―
