### ISSUE TITLE
弹幕姬导致全屏游戏跳出的问题

### ISSUE THREAD

**Issue by TaxicoYin** [copyliu/bililive_dm#124]
再开启弹幕姬然后再用win10的那个小组件，会导致游戏在游玩的时候跳出到桌面

**Comment by CXido** [comment]
把侧边栏关掉就不会弹出桌面了
![image](https://user-images.githubusercontent.com/55381745/218732983-3d50c40e-9826-457e-be94-74c9ae5a7aa8.png)
