### ISSUE TITLE
弹幕姬与Apex英雄冲突

### ISSUE THREAD

**Issue by xiaocainiao2020** [copyliu/bililive_dm#129]
我的电脑是机械革命极光pro2023版的，系统是win11家庭版，我在玩steam平台的Apex英雄的时候经常遇到游戏突然窗口化弹出去的问题，经过我大量的对比测试终于找到了原因，发现我遇到问题的时候都是一直开着弹幕姬的，把弹幕姬关闭后游戏就没在遇到过突然窗口化的问题了。请作者大大看看这是弹幕姬的问题还是游戏的问题呢？

**Comment by copyliu** [comment]
侧边栏和全屏弹幕和全屏游戏有冲突, 请尝试试用配套的提词板
