### ISSUE TITLE
表情遮蔽功能默认开启能否关闭？

### ISSUE THREAD

**Issue by pilypily** [copyliu/bililive_dm#130]
如题，我的房间有自定义表情，且观众也会发送自定义表情，这个功能还是比较需要的，能否不要自动开启

**Comment by pilypily** [comment]
2023-06-05: 新增表情遮蔽功能(由 Shiori514 貢獻), 默認啟用.

**Comment by copyliu** [comment]
可以 , fixed by 3a0594b8a9df124d73dcb7fc8bdbd590fb985e3b
