### ISSUE TITLE
试图安装Bililive_dm时发生错误

### ISSUE THREAD

**Issue by Garyllis** [copyliu/bililive_dm#132]
试图下载“https://soft.ceve-market.org/bilibili_dm/Bililive_dm.application”时发生错误。

有关详细信息，请参阅位于“C:\Users\dell\AppData\Local\Temp\VSD4B8D.tmp\install.log”的安装日志文件。

下载链接404，挂了梯子还是404，有没有什么解决办法

**Comment by copyliu** [comment]
CDN欠费了, 刚买了, 正在等待生效
