### ISSUE TITLE
WS认证参数需要调整一下

### ISSUE THREAD

**Issue by skyatgit** [copyliu/bililive_dm#137]
问题：
由于B站前段时间的更新，会导致某些直播间收不到弹幕消息，例如：https://live.bilibili.com/23053924
原因：
检查过后发现当WS认证时{ roomid = channelId, uid = 0, protover = 3, key = token, platform = "danmuji", type = 2 };
数据中的uid为0时会出现这个问题
解决方法：
uid随便填一个或者通过下面这个接口可用获取到主播的uid
`private static (int?, long?) GetRoomIdAndUid(int shortRoomId)
    {
        var url = $"https://api.live.bilibili.com/xlive/web-room/v1/index/getRoomBaseInfo?room_ids={shortRoomId}&req_biz=web/";
        var result = new HttpClient().GetStringAsync(url).Result;
        var jsonResult = (JObject)JsonConvert.DeserializeObject(result);
        var roomInfo = (JObject)jsonResult?["data"]?["by_room_ids"]?.Values().FirstOrDefault();
        var roomId = (int?)roomInfo?.GetValue("room_id");
        var uid = (long?)roomInfo?.GetValue("uid");
        return (roomId, uid);
    }`
解决方法2：
认证消息内添加buvid字段也是可以的解决此问题的，但是推荐第一种方法
https://data.bilibili.com/v/这个接口的cookie会携带buvid
提示：
WS地址为wss://broadcastlv.chat.bilibili.com/sub时是不需要key的
所以只需要构造出`{ uid = _uid, roomid = _roomId, protover = 3, platform = "web", type = 2 };`即可
*platform =danmuji仍然可用

**Comment by copyliu** [comment]
给个1能用否

**Comment by skyatgit** [comment]
@copyliu 我测试了一下，直接给个1也行，前提是 WS连接时选择的服务器是：`wss://broadcastlv.chat.bilibili.com/sub`

**Comment by copyliu** [comment]
实测徐先生的ID可以用
B站不存在UID是1的用户

**Comment by copyliu** [comment]
fixed by  https://github.com/copyliu/bililive_dm/commit/d60591f982627bd91ebedf0b0d133d21d5fd0f41

**Comment by copyliu** [comment]
啊B这么改直播间不登录的话不就看不到弹幕了吗? 实测确实如此. ||根本不知道他们怎么想的||

**Comment by skyatgit** [comment]
不登录的话使用的是buvid那个字段，带了那个字段之后uid就可以为0了
