### ISSUE TITLE
win11专业版运行提示缺少程序运行

### ISSUE THREAD

**Issue by henghengkan** [copyliu/bililive_dm#142]
我以前是家庭版是可以正常使用的，最近升专业版就用不了了
![屏幕截图 2023-08-18 151823](https://github.com/copyliu/bililive_dm/assets/120463504/421ff7d9-21c2-4bda-8437-7a47004d0f66)

**Comment by copyliu** [comment]
系统缺核心组件, 是不是什么奇怪的精简版?

**Comment by henghengkan** [comment]
> 系统缺核心组件, 是不是什么奇怪的精简版?

不是正版，根据b站用程序刷的，这个组件能下回来么
