### ISSUE TITLE
楼主昨天跟我说缺少组件，这个能下回来吗

### ISSUE THREAD

**Issue by henghengkan** [copyliu/bililive_dm#143]
不想再改系统了，就没有别的办法了吗

T h e f o l l o w i n g p r o p e r t i e s h a v e b e e n s e t :

P r o p e r t y : [ A d m i n U s e r ] = t r u e { b o o l e a n }

P r o p e r t y : [ I n s t a l l M o d e ] = H o m e S i t e { s t r i n g }

P r o p e r t y : [ N T P r o d u c t T y p e ] = 1 { i n t }

P r o p e r t y : [ P r o c e s s o r A r c h i t e c t u r e ] = A M D 6 4 { s t r i n g }

P r o p e r t y : [ V e r s i o n N T ] = 1 0 . 0 . 0 { v e r s i o n }

R u n n i n g c h e c k s f o r p a c k a g e ' M i c r o s o f t . N E T F r a m e w o r k 4 . 6 . 2 ( x 8 6 孴 x 6 4 ) ' , p h a s e B u i l d L i s t

R e a d i n g v a l u e ' R e l e a s e ' o f r e g i s t r y k e y ' H K L M \ S o f t w a r e \ M i c r o s o f t \ N E T F r a m e w o r k S e t u p \ N D P \ v 4 \ F u l l '

R e a d i n t e g e r v a l u e 5 3 3 3 2 0

S e t t i n g v a l u e ' 5 3 3 3 2 0 { i n t } ' f o r p r o p e r t y ' D o t N e t 4 6 2 F u l l _ R e l e a s e '

R e a d i n g v a l u e ' v 4 ' o f r e g i s t r y k e y ' H K L M \ S O F T W A R E \ M i c r o s o f t \ N E T F r a m e w o r k S e t u p \ O S I n t e g r a t i o n '

R e a d i n t e g e r v a l u e 1

S e t t i n g v a l u e ' 1 { i n t } ' f o r p r o p e r t y ' D o t N e t 4 6 2 F u l l _ O S I n t e g r a t e d '

R e a d i n g v a l u e ' R e l e a s e ' o f r e g i s t r y k e y ' H K L M \ S o f t w a r e \ M i c r o s o f t \ N E T F r a m e w o r k S e t u p \ N D P \ v 4 \ F u l l \ 2 0 5 2 '

R e a d i n t e g e r v a l u e 5 3 3 3 2 0

S e t t i n g v a l u e ' 5 3 3 3 2 0 { i n t } ' f o r p r o p e r t y ' D o t N e t 4 6 2 F u l l L a n g P a c k _ R e l e a s e '

R e a d i n g v a l u e ' L C I D ' o f r e g i s t r y k e y ' H K L M \ S Y S T E M \ C u r r e n t C o n t r o l S e t \ C o n t r o l \ M U I \ U I L a n g u a g e s \ z h - C N '

R e a d i n t e g e r v a l u e 2 0 5 2

S e t t i n g v a l u e ' 2 0 5 2 { i n t } ' f o r p r o p e r t y ' D o t N e t 4 6 2 F u l l L a n g P a c k _ O S _ L C I D '

R e a d i n g v a l u e ' v 4 ' o f r e g i s t r y k e y ' H K L M \ S O F T W A R E \ M i c r o s o f t \ N E T F r a m e w o r k S e t u p \ O S I n t e g r a t i o n '

R e a d i n t e g e r v a l u e 1

S e t t i n g v a l u e ' 1 { i n t } ' f o r p r o p e r t y ' D o t N e t 4 6 2 F u l l L a n g P a c k _ O S I n t e g r a t e d '

T h e f o l l o w i n g p r o p e r t i e s h a v e b e e n s e t f o r p a c k a g e ' M i c r o s o f t . N E T F r a m e w o r k 4 . 6 . 2 ( x 8 6 孴 x 6 4 ) ' :

P r o p e r t y : [ D o t N e t 4 6 2 F u l l L a n g P a c k _ O S I n t e g r a t e d ] = 1 { i n t }

P r o p e r t y : [ D o t N e t 4 6 2 F u l l L a n g P a c k _ O S _ L C I D ] = 2 0 5 2 { i n t }

P r o p e r t y : [ D o t N e t 4 6 2 F u l l L a n g P a c k _ R e l e a s e ] = 5 3 3 3 2 0 { i n t }

P r o p e r t y : [ D o t N e t 4 6 2 F u l l _ O S I n t e g r a t e d ] = 1 { i n t }

P r o p e r t y : [ D o t N e t 4 6 2 F u l l _ R e l e a s e ] = 5 3 3 3 2 0 { i n t }

R u n n i n g c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 0 - x 8 6 - x 6 4 - A l l O S - E N U . e x e '

R e s u l t o f r u n n i n g o p e r a t o r ' V a l u e E q u a l T o ' o n p r o p e r t y ' I n s t a l l M o d e ' a n d v a l u e ' H o m e S i t e ' : t r u e

R e s u l t o f c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 0 - x 8 6 - x 6 4 - A l l O S - E N U . e x e ' i s ' B y p a s s '

R u n n i n g c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 2 - W e b . e x e '

R e s u l t o f r u n n i n g o p e r a t o r ' V a l u e N o t E q u a l T o ' o n p r o p e r t y ' I n s t a l l M o d e ' a n d v a l u e ' H o m e S i t e ' : f a l s e

R e s u l t o f r u n n i n g o p e r a t o r ' V a l u e G r e a t e r T h a n E q u a l T o ' o n p r o p e r t y ' D o t N e t 4 6 2 F u l l _ R e l e a s e ' a n d v a l u e ' 3 9 4 8 0 2 ' : t r u e

R e s u l t o f c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 2 - W e b . e x e ' i s ' B y p a s s '

R u n n i n g c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 0 - x 8 6 - x 6 4 - A l l O S - C H S . e x e '

R e s u l t o f r u n n i n g o p e r a t o r ' V a l u e G r e a t e r T h a n E q u a l T o ' o n p r o p e r t y ' D o t N e t 4 6 2 F u l l L a n g P a c k _ R e l e a s e ' a n d v a l u e ' 3 9 4 8 0 2 ' : t r u e

R e s u l t o f c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 0 - x 8 6 - x 6 4 - A l l O S - C H S . e x e ' i s ' B y p a s s '

R u n n i n g c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 0 - x 8 6 - x 6 4 - A l l O S - C H S . e x e '

R e s u l t o f r u n n i n g o p e r a t o r ' V a l u e G r e a t e r T h a n E q u a l T o ' o n p r o p e r t y ' D o t N e t 4 6 2 F u l l L a n g P a c k _ R e l e a s e ' a n d v a l u e ' 3 9 4 8 0 2 ' : t r u e

R e s u l t o f c h e c k s f o r c o m m a n d ' D o t N e t F X 4 6 2 \ N D P 4 6 2 - K B 3 1 5 1 8 0 0 - x 8 6 - x 6 4 - A l l O S - C H S . e x e ' i s ' B y p a s s '

' M i c r o s o f t . N E T F r a m e w o r k 4 . 6 . 2 ( x 8 6 孴 x 6 4 ) ' R u n C h e c k r e s u l t : N o I n s t a l l N e e d e d

L a u n c h i n g A p p l i c a t i o n .

A p p l i c a t i o n a p p e a r s t o b e a n a p p l i c a t i o n m a n i f e s t

L a u n c h i n g a p p l i c a t i o n m a n i f e s t v i a d f s h i m

**Comment by henghengkan** [comment]
请问是这里面的其中一个吗

![屏幕截图 2023-08-19 090649](https://github.com/copyliu/bililive_dm/assets/120463504/5a34d754-a55a-4abb-b124-3a7d67a124c4)

**Comment by henghengkan** [comment]
还是不可以

**Comment by copyliu** [comment]
沒有聽說過被精簡掉.NET運行庫之後怎麼弄回來的先例, 不如說我自己甚至也不知道怎麼把這個東西從系統剝離...
這個理應是系統核心內容...

**Comment by henghengkan** [comment]
就是nef咯，好的

> 沒有聽說過被精簡掉.NET運行庫之後怎麼弄回來的先例, 不如說我自己甚至也不知道怎麼把這個東西從系統剝離... 這個理應是系統核心內容...

就是说缺少的是nef咯，好的，我去试试

**Comment by copyliu** [comment]
彈幕姬要求.NET版本是4.6.1, 這個會在win10的最早版本就會自帶.
你可以嘗試安裝一下剛發佈的4.8.1試試

另外你看到的諸如.NET 5 6 7 8均不是彈幕姬要求的版本, 本質上來講這些和.NET 4並不是同一個東西

**Comment by henghengkan** [comment]
> 彈幕姬要求.NET版本是4.6.1, 這個會在win10的最早版本就會自帶. 你可以嘗試安裝一下剛發佈的4.8.1試試
> 
> 另外你看到的諸如.NET 5 6 7 8均不是彈幕姬要求的版本, 本質上來講這些和.NET 4並不是同一個東西

我现在在微软net官网，他们历史版本只提供了1 2 3 5系唯独没看到4，这是什么情况

**Comment by henghengkan** [comment]
找到了，我只下载x64就可以了是吧楼主

**Comment by copyliu** [comment]
https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/net481

**Comment by henghengkan** [comment]
> 彈幕姬要求.NET版本是4.6.1, 這個會在win10的最早版本就會自帶. 你可以嘗試安裝一下剛發佈的4.8.1試試
> 
> 另外你看到的諸如.NET 5 6 7 8均不是彈幕姬要求的版本, 本質上來講這些和.NET 4並不是同一個東西

是这个吗

![image](https://github.com/copyliu/bililive_dm/assets/120463504/dc42981f-6544-447e-8e44-434a0960015f)

**Comment by henghengkan** [comment]
> 彈幕姬要求.NET版本是4.6.1, 這個會在win10的最早版本就會自帶. 你可以嘗試安裝一下剛發佈的4.8.1試試
> 
> 另外你看到的諸如.NET 5 6 7 8均不是彈幕姬要求的版本, 本質上來講這些和.NET 4並不是同一個東西

好的，所以不是4的下载都没用是吧

**Comment by henghengkan** [comment]
> 沒有聽說過被精簡掉.NET運行庫之後怎麼弄回來的先例, 不如說我自己甚至也不知道怎麼把這個東西從系統剝離... 這個理應是系統核心內容...
我百度了.NET的文件位置，但是我明明已经安装4.8.1而且重启了，我是没找到6.1但是6.2也提示我拥有更高版本，弹幕姬还是打不开，大佬，我需要它

![image](https://github.com/copyliu/bililive_dm/assets/120463504/c5c55e54-0513-4a24-8aa8-c9b4452b012a)

![image](https://github.com/copyliu/bililive_dm/assets/120463504/1c22d857-dfc2-4977-96c7-8716db9b64ed)

**Comment by henghengkan** [comment]
忘记跟大佬说了，我搞不好，所以我把系统退回了，话说官网的插件中心我看有几个插件提到了登录中心，在哪哇
