### ISSUE TITLE
关于收不到弹幕的问题

### ISSUE THREAD

**Issue by Dengzixu** [copyliu/bililive_dm#145]
最近发现有时候会收不到弹幕消息，然后进行了亿点简短的测试，以下仅为测试的猜测结果。

在请求 `https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo` 的时候需要携带 Cookie。Cookie 中只需要包含 `SESSDATA` 即可。

在进行身份认证的时候，`uid` 字段需要与 `SESSDATA` 所有者的 UID 相对应。

**时间有限，仅做了一部分测试，希望作者能参考并帮助测试一下。**

**Comment by copyliu** [comment]
但這需要登陸, 彈幕姬不會使用登陸的方式

**Comment by Dengzixu** [comment]
目前只有在身份认证时将UID设置为 `0`，才能不丢消息，但是又看不到用户名，好难办啊。

**Comment by Dengzixu** [comment]
> why close?

目前也没有更好的解决方案，如果有的话在 Reopen 吧

**Comment by copyliu** [comment]
方案倒是有, 走开放平台也不是不行, 见 https://t.bilibili.com/768514686210539521

**Comment by iwxyi** [comment]
现在有解决方案了吗？

**Comment by iwxyi** [comment]
> 目前只有在身份认证时将UID设置为 `0`，才能不丢消息，但是又看不到用户名，好难办啊。

登录的话有能获取到用户名的方案吗？

**Comment by passby6someone** [comment]
> > 目前只有在身份认证时将UID设置为 `0`，才能不丢消息，但是又看不到用户名，好难办啊。
> 
> 登录的话有能获取到用户名的方案吗？

我测了下，在请求 https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo 的时候带上cookie，拿着响应的token在WS鉴权是可以获取到用户名的

**Comment by copyliu** [comment]
duplicate #144
