### ISSUE TITLE
怎么把‘xx进入了直播间’屏蔽？一直刷屏看不清弹幕了

### ISSUE THREAD

**Issue by agni-bumi** [copyliu/bililive_dm#146]

**Comment by 1265578519** [comment]
![image](https://github.com/copyliu/bililive_dm/assets/6442439/b7a53126-5337-48e8-bea3-9d8ec0c4d21e)
取消“观众互动”

**Comment by agni-bumi** [comment]
> ![image](https://user-images.githubusercontent.com/6442439/269407499-b7a53126-5337-48e8-bea3-9d8ec0c4d21e.png) 取消“观众互动”

原来如此，我还以为这个是弹幕内容相关的
