### ISSUE TITLE
直播页面这个api可以显示实时房间在线人数

### ISSUE THREAD

**Issue by 1265578519** [copyliu/bililive_dm#148]
入口：https://link.bilibili.com/p/center/index#/shop/live-control

相关api
https://api.live.bilibili.com/xlive/e-commerce-interface/v1/ecommerce-anchor/anchor_get_center_console_data_panel

可能需要申请直播带货权限？

响应参数
"room_uv": "76"

此值为房间内实时人数，而不是那种累积的观看次数

**Comment by copyliu** [comment]
```{"code":1302002,"message":"您当前没有相关权限","ttl":1,"data":null}```

應該是要帶貨權限的. 因為不是普適性接口, 就...不做了吧

**Comment by 1265578519** [comment]
![image](https://github.com/user-attachments/assets/0add8a59-2acb-48d0-9715-642fa02a1be8)

官方新出了个接口，并且能显示所有在线人数的ID和用户名，能加吗？

**Comment by copyliu** [comment]
原則上因為彈幕姬需要符合啊B開放平台的合規化政策, 因此開放平台不給的數據就是無法接
