### ISSUE TITLE
[功能建议] 超管切断直播时，在题词版中发出提示信息。

### ISSUE THREAD

**Issue by Akarinnnnn** [copyliu/bililive_dm#153]
超管可能在没有事先发出警告的情况下，直接切断直播（上星期体验过一次，至今客服还没给具体封禁原因）。当时弹幕姬和题词版都没有发出提示信息，直到10分钟后切到obs才发现被掐了。单显示器用户可能对着空气播半天才发现不对。

**Comment by copyliu** [comment]
有没有可能是有警告而你不知道?

弹幕姬现在是收不到超管警告的, 更收不到直播已关闭的信息
