### ISSUE TITLE
“侧提示字型”设置项 在重新启动弹幕姬后失效

### ISSUE THREAD

**Issue by DriftingDooooooge** [copyliu/bililive_dm#154]
在中文Windows系统上，侧边文字默认是**微软正黑**。在设置里将其更改为其他字体，仅在本次使用有效。第二次打开弹幕姬，又变回**微软正黑**了。（设置项中还是上次选择的字体，但是实际显示变回了**微软正黑**）
![屏幕截图 2023-09-27 173649](https://github.com/copyliu/bililive_dm/assets/31515081/823a362c-1a43-40a1-95d3-dc4de8a14a69)

**Comment by copyliu** [comment]
fixed by https://github.com/copyliu/bililive_dm/commit/f78c33072583fa009b6bc9a2498ffc4f4666db94
