### ISSUE TITLE
弹幕姬的弹幕中的isAdmin这些属性似乎失效了

### ISSUE THREAD

**Issue by luiguangguan** [copyliu/bililive_dm#156]
isAdmin失效了，可以看下图，是不是阿B改了规则导致的

![image](https://github.com/copyliu/bililive_dm/assets/20753694/cb4f80b8-0102-46ab-aa5a-8f521cb68831)

**Comment by copyliu** [comment]
是的, 啊B不给相关数据了

**Comment by luiguangguan** [comment]
不登陆看直播，弹幕列表还是有房管标识，是否可以通过这个来标记房管
