### ISSUE TITLE
用戶進入直播間的訊息無法顯示

### ISSUE THREAD

**Issue by ZforVendetta** [copyliu/bililive_dm#157]
即使勾選觀客互動，仍然無法顯示用戶進入直播間的訊息(例：XXXXX進入了直播間)。
我勾選了保存日誌的項目，但是不知道日誌文件的保存路徑。
如果您能就此問題進行回復，那將非常有幫助，十分感謝！

OS：Windows 10 Pro 22H2
軟體版本：1.1.1.115
下圖是我的軟體配置：
![image](https://github.com/copyliu/bililive_dm/assets/31807940/e14cef5e-e939-4832-a865-d6c0bad1ed99)

**Comment by copyliu** [comment]
根據B站要求在切換到B站新接口後, 用戶進入直播間信息B站已不提供, 已向B站提出了需求看看他們要不要弄.

日誌文件在 `本機\文件\弹幕姬` 里
