### ISSUE TITLE
B站弹幕姬提词板 无法安装

### ISSUE THREAD

**Issue by tieniu1** [copyliu/bililive_dm#161]
您的工具很好用，但是能否提供一个“B站弹幕姬提词板”的安装包链接？
我的 windows stroe 无法安装更新和安装任何应用，“B站弹幕姬提词板”点击“安装”没有任何效果。

我试了很多方法重置 windows stroe 都没用，已经放弃了。

**Comment by copyliu** [comment]
很遺憾做不到, 提詞板由於需要使用系統內置的兇箱插件提供全屏模式功能, 他必須是一個UWP形式的程序, 也就是除非開發者模式只能通過商店安裝. 而且, 也只有商店安裝的UWP程序在非開發者模式下才有可能和外部程序聯動.
