### ISSUE TITLE
希望可以添加到开始菜单磁贴中

### ISSUE THREAD

**Issue by LeopoldChou** [copyliu/bililive_dm#162]
由程序创建的 Application Reference (.appref-ms) 的快捷方式不能放到 Windows 10 的开始菜单磁贴中，试了很多办法都放不进去；直接由程序的 .exe 创建的快捷方式又不能启动程序，希望有解决办法

**Comment by JackHaozhu** [comment]
其实程序有在开始菜单添加快捷方式的，只不过不在B开头那一栏，在CopyLiu文件夹里（
可以直接固定到开始菜单的
![PixPin_2024-06-23_07-20-09](https://github.com/copyliu/bililive_dm/assets/113544193/e5935174-7c82-4ae9-82fd-7f042c284624)
