### ISSUE TITLE
进入和观众数无法监听？

### ISSUE THREAD

**Issue by zswodegit** [copyliu/bililive_dm#166]
在Class1_ReceivedRoomCount 里面调用e.UserCount，这个数值永远都是不变的
在Class1_ReceivedDanmaku 里调用
if (e.Danmaku.InteractType == InteractTypeEnum.Enter)
{
  this.log("print someting");
  // do something
}
也是没有任何效果，完全不进入这个if条件
同样的尝试了
if (e.Danmaku.MsgType == MsgTypeEnum.Welcome) 和 if(e.Danmaku.MsgType.Equals(InteractTypeEnum.Enter)) 都是不行？

**Comment by copyliu** [comment]
弹幕姬改到啊B开放平台之后，啊B开放平台不下发这些数据了，还在争取中，如果有收到的话会触发这些事件

在 2024年4月7日週日 17:34，zswodegit ***@***.***> 寫道：
