### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by Epxoxy** [copyliu/bililive_dm#17]
我是使用了您的DanmakuLoader相关的类构建我的程序，仅仅在原文件的基础上修改了一下调试输出信息，然后引用进我构建的程序，一切在多天的开发中都没有什么问题，直到今天我碰到了一个希望却无法重现的OutOfMemory异常，由DanmakuLoader.cs:line 177导致，后面再次测试的时候，使用过相同或者不同的RoomId，但是也没能再次发现这个异常，由于对bilibili的api不太了解，我不太清楚原因，我将当时的一些调试输出信息贴上，希望有空可以指教下。`
![error](https://user-images.githubusercontent.com/19747520/29496099-5922f36e-85fe-11e7-9b66-5023c4b231a4.png)

**Comment by copyliu** [comment]
https://github.com/copyliu/bililive_dm/blob/master/BiliDMLib/DanmakuLoader.cs#L177

我觉得这一行应该不会OOM吧.......不知道你的177行是什么内容

**Comment by Epxoxy** [comment]
此外在https://github.com/copyliu/bililive_dm/blob/4c062c23206084cb2f317e28e9b0ba4615516b35/BiliDMLib/utils.cs#L27里，希望能做一个空值检查

**Comment by Epxoxy** [comment]
![error](https://user-images.githubusercontent.com/19747520/29500504-b388cd88-8653-11e7-9834-f6aea08394cd.png)

**Comment by Genteure** [comment]
数据整体读偏了，读到的不是包长度。

猜测发生原因：
1. 你发现弹幕连接会偶尔抛出 `ObjectDisposedException`
2. 发现是由 [这里](https://github.com/copyliu/bililive_dm/blob/4c062c23206084cb2f317e28e9b0ba4615516b35/BiliDMLib/utils.cs#L30) 抛出来的
3. 做了一个“空值检查”阻止了抛错
4. 导致该方法没有读够指定量的 bytes 就返回了
5. 导致数据流整体向左读偏几个字节（少读了几个字节）
6. 导致主循环里，读了一个不是包长度的巨大数字作为包长度
7. 导致抛出了 `OutOfMemoryException`

**Comment by Epxoxy** [comment]
我只更改了原文件的调试输出，其他任何东西包括空值检查我没有加上去
空异常一般在我断开连接时抛出，OOM异常一般在刚连接上时抛出

**Comment by copyliu** [comment]
数据整体读偏导致的包长度异常的大然后开buffer数组导致的OOM, 你最好重新确认下你是否动过整个流程, 是否出现了少读或者多读数据的问题.

**Comment by Epxoxy** [comment]
流程我没有动过，确定了一下在OOM前抛出了一个JSON转换的异常，原因是JSON格式错误，数据少读了
![jsonerror](https://user-images.githubusercontent.com/19747520/29503643-135a11aa-866c-11e7-9e38-99de62429515.PNG)

**Comment by copyliu** [comment]
建议你贴代码
