### ISSUE TITLE
试图安装bililive_dm时发生错误

### ISSUE THREAD

**Issue by sxinxins** [copyliu/bililive_dm#20]
![default](https://user-images.githubusercontent.com/30524883/34150527-8537f38e-e4e3-11e7-9395-3bfbcb4a161b.png)

**Comment by sxinxins** [comment]
详细信息：试图下载“http://soft.ceve-market.org/bilibili_dm/Bililive_dm.application”时发生错误。

**Comment by sxinxins** [comment]
启动VPN之后能正常运行，是因为地址被墙了？

**Comment by copyliu** [comment]
被运营商插了什么奇怪东西了吧, 所以安装地址早就更改到https了, 因为在B站CDN里的安装包实在无法更新了,
就姑且这样了
