### ISSUE TITLE
给房管助手重制版提一个建议：弹幕列表和礼物列表拆分，并省略文字前缀

### ISSUE THREAD

**Issue by iblueer** [copyliu/bililive_dm#28]
在看warma直播的时候[^1]，发现实时弹幕框里面，`弹幕`和`礼物`混杂在一起，对于观看体验有负面影响，所以真诚地对此提出改进的建议。

[^1]: warma世界第一可爱

希望开发者可以关于此事稍稍考虑。

![a7c7539c-2c8a-4091-850e-9a475b51d27e](https://user-images.githubusercontent.com/3581944/51075419-14cfa900-16c6-11e9-8fcc-024cda2b221d.png)

**Comment by Genteure** [comment]
如果你是说那个插件的话，应该找 @Executor-Cheng

**Comment by iblueer** [comment]
感谢！我从那个插件的官网点过来的，没想到不是同一个项目。

**Comment by copyliu** [comment]
插件都是由各个插件作者自行编写, 请咨询对应插件的作者

**Comment by Executor-Cheng** [comment]
※房管助手重制版插件并没有接管弹幕姬的ProcDanmaku线程
照你所说的情况来看，应该是弹幕姬本身的日志输出问题。
