### ISSUE TITLE
点歌姬几个问题咨询

### ISSUE THREAD

**Issue by ArthurFerdinand** [copyliu/bililive_dm#29]
1.点歌姬v3里好像找不到歌词行数的设置
2.点歌姬歌词模板没有提供可用对象的列表，用户只知道demo里的类似{{播放列表}}这样的对象

**Comment by Genteure** [comment]
点歌姬v3 在 [这](https://github.com/Bililive/DGJv3)，这个仓库是弹幕姬。
点歌姬目前处于暂停维护状态，太花时间了，而且没什么兴趣了，就放置了。
可以使用 `{{ this }}` 输出全部变量的信息，源码参考[这里](https://github.com/Bililive/DGJv3/blob/ea5d8928c6d546e15ae041f5a68661850e8b02de/DGJv3/Writer.cs#L100-L109)。
