### ISSUE TITLE
弹幕姬的弹幕是否可能长期显示？

### ISSUE THREAD

**Issue by iavas** [copyliu/bililive_dm#31]
如题，目前版本的弹幕最多显示7秒，是否可能将其设置调整为——没有新弹幕顶替时，旧弹幕在弹幕区域持续长时间显示？

**Comment by copyliu** [comment]
会导致资源爆炸的你确定需要？

Li Jian <notifications@github.com> 於 2019年5月4日 週六 00:07 寫道：
