### ISSUE TITLE
bilibili弹幕系统,已经收不到弹幕了

### ISSUE THREAD

**Issue by slinar** [copyliu/bililive_dm#32]
弹幕系统升级, 以下是bilibili直播的官方动态
https://t.bilibili.com/258961230595770167?tab=2

**Comment by gwy15** [comment]
实际上WS还是能收到弹幕的，不知道为什么弹幕姬也收不到
![Snipaste_2019-05-29_21-52-01](https://user-images.githubusercontent.com/23229760/58562548-0ee4f980-825c-11e9-9038-adb4a6bef64a.png)

**Comment by slinar** [comment]
cmd不一样了

**Comment by copyliu** [comment]
fixed by https://github.com/copyliu/bililive_dm/commit/75e883202ba77d8627e0e7b87cd4f696358e7244
