### ISSUE TITLE
b站弹幕更改API

### ISSUE THREAD

**Issue by wudifeixue** [copyliu/bililive_dm#33]
由于全网弹幕升级，b站弹幕已经在不惜牺牲旧客户端的情况下改了接口。

我本来想自己试试修一下弹幕姬直接提交PR了，但是我发现我怎么都没办法自己build成功，有点过于头疼就来发issue了。

总之代码应该是改这里：https://github.com/copyliu/bililive_dm/blob/5f2881db0cc516a7185cf2916217361e995828b8/BilibiliDM_PluginFramework/DanmakuModel.cs#L237

相关修复讨论有这个：https://github.com/3Shain/BiliChat/pull/42

**Comment by Genteure** [comment]
昨天已经改过了

**Comment by wudifeixue** [comment]
啊，我看到commit了，但是无法正常使用..

**Comment by Genteure** [comment]
如果你使用的是 Windows XP 或 Windows Vista 或 Windows 7 without Service Pack 1 那弹幕姬现在不支持你的系统了
弹幕姬现在从 .NET Framework 4 改到了 .NET Framework 4.6.1

如果你有使用弹幕姬插件，因为弹幕姬修改了 .NET Framework 和 Newtonsoft.Json 的版本，导致部分插件出错，甚至崩溃了整个进程。把插件文件从插件文件夹移出可以解决。

**Comment by wudifeixue** [comment]
操作系统win10最新版，安装包使用的官网版直接安装更新的。

重复步骤，使用版本号1.1.1.1, 连接直播间13946381，测试发送弹幕，效果是显示正在链接，链接成功，然后发弹幕测试无效。

![image](https://user-images.githubusercontent.com/7316929/58610775-f54aae80-8269-11e9-8645-10d55715d89a.png)

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/58610794-6b3d2d00-82df-11e9-9c24-c8bd9a16c639.png)
你被禁言了之类的吧？F12看一下send接口返回了啥

**Comment by wudifeixue** [comment]
晕了，看来反馈用户和我自己都是海外用户。而且又被限制了。

![image](https://user-images.githubusercontent.com/7316929/58610951-9e91a480-826a-11e9-9bab-b6ec82bc7891.png)

我看到你弹幕了，感谢解答。
