### ISSUE TITLE
请教礼物实时获取的实现原理

### ISSUE THREAD

**Issue by honhosing** [copyliu/bililive_dm#34]
由于我的电脑是MacOS，因此无缘直接使用弹幕姬（除非装双系统），于是我用Python写了个轻型程序，用于监控关注粉丝变化，并通过POST的方法发感谢弹幕和定时的欢迎弹幕。所以想再增加一些功能，比如**感谢礼物**。

在分析礼物信息来源时，发现这个数据应该是通过JS控制下面的div容器实现的

```
<div class="penury-gift-msg w-100 p-relative over-hidden" id="penury-gift-msg">
  <div class="penury-gift-item v-middle a-move-out-bottom">
    <span class="username v-middle">某位粉丝的姓名</span>
    <span class="action v-middle">喂食辣条</span>
    <div class="dp-i-block v-middle">
      <div class="gift-frame gift-1-20" style="width: 20px; height: 20px;"></div>
    </div>
    <span class="count">X 1</span>
  </div>
</div>
```

由于我使用Python习惯直接通过URL来GET和POST来实现某个功能，如果直接将整个网页的代码GET下来再解析并正则匹配的话效率太低，我看了下弹幕姬官网上是安装插件实现的，但dll文件没法解读，所以想请教一下您在这方面是如何实现的 ？

**Comment by yyc12345** [comment]
发送弹幕是插件的部分，和弹幕姬本身的接口应该没有关系。这部分的作者是其他人，建议在对应[repo里面](https://github.com/Bililive/SendDanmaku)提issue或者直接寻找作者：宅急送队长

顺带一提，我也曾经有过这类想法，因为我想把工程移植到.Net Core平台。然后根据我的猜测，它可能是用了登陆插件，然后在此基础上做了弹幕发送的接口。登录是LoginCenter.dll，但是这个插件没有源代码提供（也对作者不开源码表示理解）。然后我去查了整个Github上的bilibili的API，想知道怎么登录，怎么发直播弹幕，但毫无结果。。。

然后我在逆向这个由ConfuserEx混淆的库之后看到了这句话：
```csharp
public const string tip = "与其逆向插件，不如浏览器调试B站╮(\uffe3▽\uffe3)╭弹幕姬相关开发讨论群553934452";
```

也许有帮助。。。

**Comment by Genteure** [comment]
你现在是请求的 `https://api.live.bilibili.com/ajax/msg` 这个接口吗？
礼物消息和一大堆其他消息都是只在弹幕服务器里传输，msg那个接口只返回最新十条弹幕。
弹幕服务器现在有 `tcp` `ws` `wss` 三个协议，里面传输的内容是一样的。
参考接口
`https://api.live.bilibili.com/room/v1/Danmu/getConf`
`https://live.bilibili.com/api/player?id=cid:1001`
参考代码部分 [DanmakuLoader.cs](https://github.com/copyliu/bililive_dm/blob/master/BiliDMLib/DanmakuLoader.cs)

登录插件是我做的，因为不想让别人通过这个插件了解怎么实现登录B站，所以用了混淆。
如果你想自己实现登录的话，可以直接去浏览器登录页 F12 大法或者逆向B站客户端，或者去看 GitHub 上其他十万个人写的B站登录（
如果就单纯的自己使用的话，没必要实现登录，直接从浏览器里 Ctrl C V 一个 cookie 过来就行了。

**Comment by Executor-Cheng** [comment]
`https://api.live.bilibili.com/gift/v3/live/gift_config` 这是礼物信息的接口，b站的所有礼物都在这里边有详细的信息。
等到你看完 `DanmakuLoader.cs`和`DanmakuModel.cs`后，请先通过`DanmakuModel.MsgType`确定消息类型后再使用`DanmakuModel.RawDataJToken["data"]["giftId"]`与接口内的id对应
以下是该接口中一个礼物的Model:
```json
{
	"id": 1,
	"name": "辣条",
	"price": 100,
	"type": 4,
	"coin_type": "silver",
	"bag_gift": 0,
	"effect": 0,
	"corner_mark": "",
	"corner_background": "",
	"broadcast": 0,
	"draw": 0,
	"stay_time": 3,
	"animation_frame_num": 13,
	"desc": "辣条是流行于哔哩哔哩的坊间美食，可以直接食用，也能用来打赌。",
	"rule": "",
	"rights": "当前主播亲密度+1 经验值+100",
	"privilege_required": 0,
	"count_map": [{
		"num": 1,
		"text": ""
	}, {
		"num": 10,
		"text": ""
	}, {
		"num": 99,
		"text": ""
	}, {
		"num": 520,
		"text": ""
	}],
	"img_basic": "https://s1.hdslb.com/bfs/live/d57afb7c5596359970eb430655c6aef501a268ab.png",
	"img_dynamic": "https://i0.hdslb.com/bfs/live/d57afb7c5596359970eb430655c6aef501a268ab.png",
	"frame_animation": "https://i0.hdslb.com/bfs/live/85d4be8c3dea80e6de6c249dbd15d6e8090125f4.png",
	"gif": "https://i0.hdslb.com/bfs/live/d40ff17d533047cbb9b2bed4feb927cb0e71901c.gif",
	"webp": "https://i0.hdslb.com/bfs/live/07d4dad91d7f68d92cb6a324ad9395ae2adefd47.webp",
	"full_sc_web": "",
	"full_sc_horizontal": "",
	"full_sc_vertical": "",
	"full_sc_horizontal_svga": "",
	"full_sc_vertical_svga": "",
	"bullet_head": "",
	"bullet_tail": "",
	"limit_interval": 0,
	"gift_type": 0
}
```

**Comment by copyliu** [comment]
弹幕姬有计划重写, 也在重写中. 大部分库会用.net standard 2, 插件系统全部推倒重做 (但保留旧插件系统接口做后向兼容)
另外此issue和本项目不相关, 暂且关闭
