### ISSUE TITLE
vs2017构建失败 找不到文件？

### ISSUE THREAD

**Issue by Night12138** [copyliu/bililive_dm#36]
![image](https://user-images.githubusercontent.com/43197204/62233623-84577c80-b3fb-11e9-9590-bc4a9cd502b1.png)

**Comment by copyliu** [comment]
错误发全一下，被折叠了

Night12138 <notifications@github.com> 於 2019年8月1日 週四 01:27 寫道：

**Comment by Night12138** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find file 'Win32\libwtfdanmaku.dll'.	Bililive_dm			
Error		Could not find file 'x64\libwtfdanmaku.dll'.	Bililive_dm			
Error	MSB1009	Project file does not exist.	wtf_lib_builder	C:\Users\Wei\Documents\cswork\bililive_dm-master\wtf_lib_builder\MSBUILD	1	
Error	MSB1009	Project file does not exist.	wtf_lib_builder	C:\Users\Wei\Documents\cswork\bililive_dm-master\wtf_lib_builder\MSBUILD	1	
Error	MSB3073	The command "Build_Debug.bat
:VCEnd" exited with code 1.	wtf_lib_builder	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	128

**Comment by Genteure** [comment]
你有没有安装 `Desktop development with C++` ？
![](https://docs.microsoft.com/en-us/cpp/build/media/vscpp-concierge-choose-workload.gif)
https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation

**Comment by Night12138** [comment]
> 你有没有安装`Desktop development with C++`？[https:](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation) //docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation
> ![](https://camo.githubusercontent.com/ba30da0bd00a1b4f7c2002588420b3c4f6c9cea7/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f656e2d75732f6370702f6275696c642f6d656469612f76736370702d636f6e6369657267652d63686f6f73652d776f726b6c6f61642e676966)
> [](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation)

安装的啦

**Comment by Night12138** [comment]
已经解决，是我没有仔细检查文件，直接git下来的没有包含ref的内容，手动再去抓取ref内容到文件夹解决了。
