### ISSUE TITLE
弹幕姬打不开

### ISSUE THREAD

**Issue by NTDLX** [copyliu/bililive_dm#37]
今天打开弹幕姬，提示更新，更新之后，打开弹幕姬，只显示如下图
![image](https://user-images.githubusercontent.com/34884072/63334547-3a184a00-c36e-11e9-83eb-254215cd92c6.png)
然后就没反应了

**Comment by copyliu** [comment]
可能是被win10安全中心拦截

动漫星空-最美不过二次元 <notifications@github.com> 於 2019年8月20日 週二 17:16 寫道：
