### ISSUE TITLE
弹幕姬开启新弹幕引擎与upupoo壁纸软件存在冲突

### ISSUE THREAD

**Issue by aihuanxiangdexiaohuzi** [copyliu/bililive_dm#39]
![~DJ8WXTS9WFT04I@Q L_(DD](https://user-images.githubusercontent.com/20015742/68670412-d7f36d80-0587-11ea-9a81-fee0cd39b9d3.png)
这个功能是否启用了全屏？导致upupoo软件停止工作，并且存在点歌姬界面白屏，只能重启解决

**Comment by Genteure** [comment]
没有全屏，但是有新建透明窗体，置顶覆盖在大半个屏幕上面。这个新弹幕引擎渲染用的是 Direct2D。不了解 upupoo 但是我看他网站上写着 "智能识别游戏场景为游戏留出更多性能空间"，我猜是他把弹幕姬判定成游戏在渲染画面了，如果是这样的话我觉得你去找 upupoo 反馈比较好一些。

点歌姬界面白屏的问题以前研究了很久，可能是用的 material design UI 库的问题，不知道具体原因是什么，凑合吧（（
因为维护起来很费劲又非常非常花时间，还有一些其他原因，所以现在点歌姬插件不维护更新了。

**Comment by Gynomys** [comment]
点歌姬好遗憾，最近都没上来看都不知道不维护了，我说咋不能用了
