### ISSUE TITLE
利用monodevelop 在linux编译时报错 系统archlinux 64bit 如果有时间可否帮我看下报错的原因

### ISSUE THREAD

**Issue by ruizhipeng** [copyliu/bililive_dm#4]
Building Solution: Bililive_dm (Debug)

Building: BilibiliDM_PluginFramework (Debug)

Build started 2015/11/16 3:55:18.
__________________________________________________
Project "/home/roy/Downloads/bililive_dm/BilibiliDM_PluginFramework/BilibiliDM_PluginFramework.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	
	Target ResolveAssemblyReferences:
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PresentationCore' not resolved
		For searchpath {CandidateAssemblyFiles}
		Warning: {CandidateAssemblyFiles} not supported currently
		For searchpath {HintPathFromItem}
		HintPath attribute not found
		For searchpath {TargetFrameworkDirectory}
		Considered target framework dir /usr/lib/mono/4.0, assembly named 'PresentationCore' not found.
		For searchpath {PkgConfig}
		Considered PresentationCore, but could not find in any pkg-config files.
		For searchpath {GAC}
		Considered PresentationCore, but could not find in the GAC.
		For searchpath {RawFileName}
		For searchpath bin/Debug/
/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PresentationFramework' not resolved
		For searchpath {CandidateAssemblyFiles}
		Warning: {CandidateAssemblyFiles} not supported currently
		For searchpath {HintPathFromItem}
		HintPath attribute not found
		For searchpath {TargetFrameworkDirectory}
		Considered target framework dir /usr/lib/mono/4.0, assembly named 'PresentationFramework' not found.
		For searchpath {PkgConfig}
		Considered PresentationFramework, but could not find in any pkg-config files.
		For searchpath {GAC}
		Considered PresentationFramework, but could not find in the GAC.
		For searchpath {RawFileName}
		For searchpath bin/Debug/
	
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	
	Target GenerateTargetFrameworkMonikerAttribute:
	Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
	
	Target CoreCompile:
		Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/BilibiliDM_PluginFramework.dll DMPlugin.cs DanmakuModel.cs Events.cs GiftRank.cs Properties/AssemblyInfo.cs /target:library /define:"DEBUG;TRACE" /nostdlib /reference:/usr/lib/mono/4.0/System.dll /reference:/usr/lib/mono/4.0/System.Xaml.dll /reference:/usr/lib/mono/4.0/System.Xml.Linq.dll /reference:/usr/lib/mono/4.0/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.0/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.0/System.Data.dll /reference:/usr/lib/mono/4.0/System.Xml.dll /reference:/usr/lib/mono/4.0/WindowsBase.dll /reference:../packages/Newtonsoft.Json.7.0.1/lib/net40/Newtonsoft.Json.dll /reference:../packages/JetBrains.Annotations.10.0.0/lib/net20/JetBrains.Annotations.dll /reference:/usr/lib/mono/4.0/System.Core.dll /reference:/usr/lib/mono/4.0/mscorlib.dll /warn:4
DMPlugin.cs(33,17): error CS0103: The name `MessageBox' does not exist in the current context
DMPlugin.cs(64,17): error CS0103: The name `MessageBox' does not exist in the current context
DMPlugin.cs(95,17): error CS0103: The name `MessageBox' does not exist in the current context
DMPlugin.cs(127,17): error CS0103: The name `MessageBox' does not exist in the current context
DMPlugin.cs(232,30): error CS0103: The name `Application' does not exist in the current context
DMPlugin.cs(248,30): error CS0103: The name `Application' does not exist in the current context
	Task "Csc" execution -- FAILED
	Done building target "CoreCompile" in project "/home/roy/Downloads/bililive_dm/BilibiliDM_PluginFramework/BilibiliDM_PluginFramework.csproj".-- FAILED
	
Done building project "/home/roy/Downloads/bililive_dm/BilibiliDM_PluginFramework/BilibiliDM_PluginFramework.csproj".-- FAILED

Build FAILED.

Warnings:

/home/roy/Downloads/bililive_dm/BilibiliDM_PluginFramework/BilibiliDM_PluginFramework.csproj (Build) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PresentationCore' not resolved
	/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PresentationFramework' not resolved

Errors:

---------------------- 完成 ----------------------

构建：6 个错误, 2 个警告

**Comment by copyliu** [comment]
mono 上并不含WPF, 而弹幕姬是使用WPF作为UI框架的. 因此编译失败. 如需利用可以研究下BiliDMLib类, 有一些基础的内容
