### ISSUE TITLE
弹幕姬安装失败，是什么问题？

### ISSUE THREAD

**Issue by sillypig79** [copyliu/bililive_dm#40]
试图下载“https://soft.ceve-market.org/bilibili_dm/Bililive_dm.application”时发生错误。

有关详细信息，请参阅位于“C:\Users\傻猪\AppData\Local\Temp\VSD6667.tmp\install.log”的安装日志文件。

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6.2 (x86 和 x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 461814
Setting value '461814 {int}' for property 'DotNet462Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet462Full_OSIntegrated'
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full\2052'
Read integer value 461814
Setting value '461814 {int}' for property 'DotNet462FullLangPack_Release'
Reading value 'LCID' of registry key 'HKLM\SYSTEM\CurrentControlSet\Control\MUI\UILanguages\zh-CN'
Read integer value 2052
Setting value '2052 {int}' for property 'DotNet462FullLangPack_OS_LCID'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet462FullLangPack_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6.2 (x86 和 x64)':
Property: [DotNet462FullLangPack_OSIntegrated] = 1 {int}
Property: [DotNet462FullLangPack_OS_LCID] = 2052 {int}
Property: [DotNet462FullLangPack_Release] = 461814 {int}
Property: [DotNet462Full_OSIntegrated] = 1 {int}
Property: [DotNet462Full_Release] = 461814 {int}
Running checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX462\NDP462-KB3151802-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet462Full_Release' and value '394802': true
Result of checks for command 'DotNetFX462\NDP462-KB3151802-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-CHS.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet462FullLangPack_Release' and value '394802': true
Result of checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-CHS.exe' is 'Bypass'
Running checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-CHS.exe'
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet462FullLangPack_Release' and value '394802': true
Result of checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-CHS.exe' is 'Bypass'
'Microsoft .NET Framework 4.6.2 (x86 和 x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697211'
Error: 试图下载“https://soft.ceve-market.org/bilibili_dm/Bililive_dm.application”时发生错误。

**Comment by copyliu** [comment]
电脑网络问题
