### ISSUE TITLE
插件如何隐藏弹幕

### ISSUE THREAD

**Issue by developer-ken** [copyliu/bililive_dm#41]
是否有可能让插件决定是否隐藏一条弹幕？
事件没有Cancell，而且弹幕的文本设为空，还是会显示原内容=_=

**Comment by copyliu** [comment]
暂时没有这个方式, 有的话事情比较麻烦

**Comment by developer-ken** [comment]
嗯，谢谢回复。我找到方法了，把弹幕类型设置为Unknown就可以不显示，不知道有没有啥潜在影响，但是功能达成了
