### ISSUE TITLE
新版弹幕协议的一些hint

### ISSUE THREAD

**Issue by AlexGuo1998** [copyliu/bililive_dm#47]
每个包是4字节长度+12字节标识符+剩下的数据
“连接成功”和“人气值”的标识符没有变化，“JSON数据”目前变为为压缩格式：
压缩数据的标识符是`0x00, 0x10, 0x00, 0x02, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00`，剩下的数据直接用`lzma`解压，可以得到旧的包结构（即：4字节长度+标识符`0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00`+JSON数据）

平时比较喜欢用您的软件，祝早日恢复！

**Comment by Genteure** [comment]
昨天已经修改，并且发了新版本了 #46
