### ISSUE TITLE
未做粘包处理？

### ISSUE THREAD

**Issue by toshiya14** [copyliu/bililive_dm#48]
大概看了看代码来学习了一下，但是我自己抓取的一部分测试数据中（我用的ws，看代码用的是tcp所以不太确定是否有相同问题），有的时候发现header里面的长度跟整体长度不匹配，然后仔细一看，数据特别多的时候，服务器直接把两段消息直接连起来丢过来了（HEADER1 BODY1 HEADER2 BODY2）。我不太确定是否会处理后面那一段数据。

而且新弹幕协议Proto=2的时候，body里面套娃，还可能出现粘包？？？（我测试的时候中有遇到）
HEADER + DEFLATEBODY(HEADER1 + BODY1 + HEADER2 + BODY2)

下面是两段我自用项目里对这个部分处理的代码。
From https://github.com/toshiya14/LiveChatLib

```C#
        /// <summary>
        /// Split binary frame might contains multiple packages into package binary data enumerable.
        /// </summary>
        /// <param name="buffer">package binary data.</param>
        /// <returns></returns>
        private static IEnumerable<byte[]> SplitBuffer(byte[] buffer)
        {
            using (var ms = new MemoryStream(buffer))
            {
                ms.Seek(0, SeekOrigin.Begin);
                using (var reader = new BinaryReader(ms))
                {
                    while (ms.Position < ms.Length)
                    {
                        var length = reader.ReadBytes(4).ByteToInt32(true);
                        if (length > buffer.Length)
                        {
                            throw new Exception("Binary frame broken, package size:" + buffer.Length + ", size in header:" + length);
                        }
                        ms.Seek(-4, SeekOrigin.Current);
                        var pack = reader.ReadBytes(length);
                        yield return pack;
                    }
                }
            }
        }
```

```C#
                using(var ms = new MemoryStream(extracted))
                {
                    ms.Seek(0, SeekOrigin.Begin);
                    using (var reader = new BinaryReader(ms))
                    {
                        do
                        {
                            var p = new Package()
                            {
                                HeadLength = headlen,
                                ProtoVer = protover,
                                Sequence = sequence
                            };
                            var msgLength = reader.ReadBytes(4).ByteToInt32(true);
                            var msgHeaderLength = reader.ReadBytes(2).ByteToInt16(true);
                            var msgVer = reader.ReadBytes(2).ByteToInt16(true);
                            var msgAc = reader.ReadBytes(4).ByteToInt32(true);
                            var msgParam = reader.ReadBytes(4).ByteToInt32(true);
                            switch (msgAc)
                            {
                                case 3:
                                    p.MessageType = MsgType.ServerHeart;
                                    break;

                                case 5:
                                    p.MessageType = MsgType.Command;
                                    break;

                                case 8:
                                    p.MessageType = MsgType.Auth;
                                    break;
                            }
                            p.Body = reader.ReadBytes((int)(msgLength - 16));
                            list.Add(p);
                        } while (ms.Length - ms.Position > 16);
                    }
                    return list;
                }
```

**Comment by Genteure** [comment]
TCP 是 Stream 流 不是 Packet 包，“粘包”是个不存在的问题，因为它**本来就不是包**。
关于“TCP粘包”这个问题网络上有大把的介绍，可以搜一下。

Websocket 是分一个一个的包的，不是流，B站可能是直接把它当做流用了。

header 里的数据长度就是用来解决“粘包”的问题的，每次只需要读header里写的那么多bytes，不要多读。

**Comment by toshiya14** [comment]
正常来说websocket应该不会粘包才是，但是不知道为何我这边是遇到两个包连在一起的情况。
而且在deflate解压之后里面的数据包也会连在一起。

**Comment by Genteure** [comment]
不是 websocket 粘包，而是B站就是这么发出来的。
你自己也说了

> 有的时候发现header里面的长度跟整体长度不匹配

那直接照着 header 里面的长度读不就好了，读完了之后如果有剩余的数据，就再读一次。
header 里放了个数据长度那肯定是有用的啊，要不然为啥白白浪费几bytes的流量（

**Comment by toshiya14** [comment]
所以说我的意思是，不太确定弹幕姬的代码里面有没有对这类情况进行处理。
如果有处理的话，就关掉issue吧。
囧

**Comment by Genteure** [comment]
有处理

这一段是读 deflate 之前的数据，先读 header 获取数据长度，再读数据本体，不多读不少读
https://github.com/copyliu/bililive_dm/blob/dc508975036d5ae45552487e0c9a939d623a1f94/BiliDMLib/DanmakuLoader.cs#L149-L162

这一段是在循环读取 deflate 之后的数据，直到没有数据可读
https://github.com/copyliu/bililive_dm/blob/dc508975036d5ae45552487e0c9a939d623a1f94/BiliDMLib/DanmakuLoader.cs#L171-L179

**Comment by toshiya14** [comment]
> 有处理
> 
> 这一段是读 deflate 之前的数据，先读 header 获取数据长度，再读数据本体，不多读不少读
> https://github.com/copyliu/bililive_dm/blob/dc508975036d5ae45552487e0c9a939d623a1f94/BiliDMLib/DanmakuLoader.cs#L149-L162

这样看的话，这段貌似只读第一条？服务器可能会扔好几个连一起的诶。(´・ω・｀)

**Comment by copyliu** [comment]
TCP没有包的概念 因此**根本没有粘包这个概念, 也不会有"粘包处理"的说法**

WS是有包的概念, 然而实际上也没有"粘包"这个概念. 你所知道的所谓"粘包"是因为某些错误的TCP流读写实现产生的伪概念. 而WS不是流, 所以没有这种错误处理流导致出来的"粘包"的错误概念...

**Comment by toshiya14** [comment]
我知道WS和TCP都没有粘包的概念，我只是说从我这边测试得到的数据是他的确有这样的现象。
也许是B站写的问题，发出来的数据的确有这样的现象。

**Comment by copyliu** [comment]
按B站当前协议, deflate之后的数据是有可能有多组数据结构. 仅此而已. 所以这边会用一个循环一直读到没有数据为止, 因为deflate部分数据是有长度, 因此解压后的数据也是能穷尽的.
https://github.com/copyliu/bililive_dm/blob/dc508975036d5ae45552487e0c9a939d623a1f94/BiliDMLib/DanmakuLoader.cs#L171-L179

**Comment by copyliu** [comment]
如果B站的WS协议是允许一个数据包放入多组数据结构，你显然是需要处理的。然而弹幕姬用的是TCP，每次读入完整的一组结构即可，由于缓冲区的存在，是不需要额外做所谓粘包处理的。
