### ISSUE TITLE
弹幕显示时程序崩溃

### ISSUE THREAD

**Issue by xiaoyao9184** [copyliu/bililive_dm#51]
“测试效果”按钮正常，收到弹幕后，弹幕显示在程序主界面中，之后程序崩溃

版本：1.1.1.28

系统日志如下：
> 应用程序: Bililive_dm.exe
> Framework 版本: v4.0.30319
> 说明: 由于未经处理的异常，进程终止。
> 异常信息: System.Reflection.TargetParameterCountException
>    在 System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
>    在 System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
>    在 System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
>    在 ExtendLogging.MainProgram.ProcDanmaku(BilibiliDM_PluginFramework.DanmakuModel)
>    在 ExtendLogging.MainProgram.<.ctor>b__52_0()
>    在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    在 System.Threading.ThreadHelper.ThreadStart()
> 
>

**Comment by Genteure** [comment]
把“更多日志”插件更新到最新版本

**Comment by yonjar** [comment]
原来如此 假如有错误提示或显示插件有更新的提示框就好了

**Comment by copyliu** [comment]
由於"更多插件"插件用了一些非公開的接口, 玩炸了本體很正常...
插件更新的提示請插件作者各自實現

我順便也會考慮要不要加個什麼統一的API
