### ISSUE TITLE
安装后出现KERNELBASE.dll错误，请问如何 解决

### ISSUE THREAD

**Issue by 1571312541** [copyliu/bililive_dm#52]
win7系统
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Bililive_dm.exe
  应用程序版本:	1.1.0.0
  应用程序时间戳:	5e9090c9
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24384
  故障模块时间戳:	5c6e248c
  异常代码:	c06d007e
  异常偏移:	000000000000be0d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	7283
  其他信息 2:	72836eb6216b49be15302fdb224c1b5d
  其他信息 3:	10bd
  其他信息 4:	10bd9f9b144e97a6172df8089ecda269

**Comment by copyliu** [comment]
不认为是弹幕姬问题, 请查看你的系统本身是否有问题
