### ISSUE TITLE
虽然很不好意思说，但改动后还没有原先好看，几个主题都太丑了，不符合现在的UI水准

### ISSUE THREAD

**Issue by lvzhenbo** [copyliu/bililive_dm#63]
如果实在不行，建议还是用原本的吧。
要不试试[材料设计语言](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit)

**Comment by copyliu** [comment]
只要主题都不选就回来了

吕振波 <notifications@github.com> 於 2020年8月26日 週三 01:54 寫道：
