### ISSUE TITLE
最近所有带版本检查的插件都出现以下错误提示

### ISSUE THREAD

**Issue by shy0511** [copyliu/bililive_dm#67]
2:22:21 : 房管助手重制版 版本检查失败 : The operation has timed out
2:22:21 : 更多日志 版本检查失败 : The operation has timed out
2:22:21 : 礼物统计 版本检查失败 : The remote name could not be resolved: 'www.danmuji.cn'
2:22:21 : 管理直播间小工具 版本检查失败 : The operation has timed out
2:23:42 : 登录中心 版本检查失败：The operation has timed out

不知道为什么。。。重装弹幕姬本体和插件也不管用。。。

**Comment by copyliu** [comment]
請咨詢插件作者
