### ISSUE TITLE
有一些人的 roomid 和 url 上不一致

### ISSUE THREAD

**Issue by lyyyuna** [copyliu/bililive_dm#7]
比如陆夫人是 http://live.bilibili.com/115
但其实他的 roomid 为 1016

需要先 GET http://live.bilibili.com/115, 
在页面上有
    <script>
        var ROOMID = 1016;
        var DANMU_RND = 1457617785;
        var NEED_VIDEO = 1;
        var ROOMURL = 115;
    </script>

我看了下，大概 url 上数字较小的几个，都不是 roomid，需要去页面上爬一下。

**Comment by copyliu** [comment]
不会修复该问题, 作为一个主播用的工具, 主播自己的roomID是肯定自己知道的, 因为是需要向B站申请(或者要求)才会分配一个URL别名. 而且主播自己也能在个人中心的直播间信息里获得自己的ID, 而无需要先看页面源码或怎么的. 所以这个问题不是问题
