### ISSUE TITLE
希望加入自定义侧边栏字体与字体颜色以及背景透明度的选项

### ISSUE THREAD

**Issue by LELEsurprise** [copyliu/bililive_dm#71]

**Comment by Luncode** [comment]
https://github.com/MoeCoding/bililive_dm-Janpese
我这份是加入了字体修改功能 可以看看

**Comment by Luncode** [comment]
样例图片：https://www.luncode.com/res/danmuku.png
程序示例：https://www.luncode.com/res/Danmaku%20Jpanese.zip

**Comment by tumuyan** [comment]
> https://github.com/MoeCoding/bililive_dm-Janpese
> 我这份是加入了字体修改功能 可以看看

不提pr嘛

**Comment by Luncode** [comment]
> > https://github.com/MoeCoding/bililive_dm-Janpese
> > 我这份是加入了字体修改功能 可以看看
> 
> 不提pr嘛

很早之前临时加的功能 后面有机会提交pr

**Comment by copyliu** [comment]
closed via #103
