### ISSUE TITLE
Feature Request : support for Multi-language 多语言支持

### ISSUE THREAD

**Issue by b4imetu** [copyliu/bililive_dm#77]
Feature Request : support for Multi-language 多语言支持
是否考虑在未来添加对简体中文和English的支持

**Comment by copyliu** [comment]
https://crowdin.com/project/bililivedm
請

**Comment by b4imetu** [comment]
感谢，考虑支持简体中文，毕竟繁体中文对于大多数人来说比较陌生

**Comment by b4imetu** [comment]
感谢。考虑支持简体中文吗？毕竟繁体中文对于大多数人来说比较陌生

**Comment by copyliu** [comment]
由于网友的激烈要求, 本软件的中文选项就是现在这个样子了
