### ISSUE TITLE
抓不到261直播间弹幕

### ISSUE THREAD

**Issue by ytwangcm** [copyliu/bililive_dm#85]
抓不到261直播间弹幕

**Comment by copyliu** [comment]
B站不存在三位数和以下的直播间, 四位数直播间也只有不到两百个是实际存在的. 请使用主播后台的真实直播间ID连接

**Comment by ytwangcm** [comment]
> B站不存在三位数和以下的直播间, 四位数直播间也只有不到两百个是实际存在的. 请使用主播后台的真实直播间ID连接

谢谢大佬
