### ISSUE TITLE
在全屏游戏时，弹幕姬会每隔一段时间抢走一次焦点，导致全屏游戏跳回桌面

### ISSUE THREAD

**Issue by NamelessAstral** [copyliu/bililive_dm#86]
WIN10环境，多屏用户。
主屏全屏游戏、副屏放弹幕姬。
用这个小软件确定了抢走焦点的应用是弹幕姬。
www.happydroid.com/focus
如果游戏无边框窗口确实不会再跳回桌面，但这样会导致游戏严重掉帧。
有点头疼，请问有什么解决方法吗。

**Comment by copyliu** [comment]
請關閉側邊欄和全屏彈幕, 試用一下提詞板.

**Comment by XBYoung** [comment]
一段时间弹出去一次
