### ISSUE TITLE
[help]打开软件出一个进度条后闪退。

### ISSUE THREAD

**Issue by gloryhui** [copyliu/bililive_dm#87]
## 求助

我有两台PC，一台是笔记本能正常打开软件，另外一台是台式机不能正常打开(win10 19043.1151版本)，一打开读个进度条就闪退了。
我尝试了删除 
``` C:\Users\用户\AppData\Local\Apps ``` 
整个文件夹进行重装，也不行。不知道是否我卸载软件的姿势对否？

---
>操作系统大版本是一样的
出现问题的是这个19043.1151这个版本。
![image](https://user-images.githubusercontent.com/11285234/128917851-d075b307-4b9d-4bd4-875f-bda368635a41.png)

![image](https://user-images.githubusercontent.com/11285234/128917978-39d4b7ea-03e7-46ee-8686-66bcc8f457f4.png)
![image](https://user-images.githubusercontent.com/11285234/128918064-e3887bde-5eff-44c6-a18a-1bd4f646e0ea.png)

**Comment by copyliu** [comment]
这个东西正常来说应该是smartscreeen跳出来要你解除, 而不是自己找到exe去解, 请考虑查看smartscreen是否工作正常
