### ISSUE TITLE
大佬的弹幕是如何实现置顶于游戏之上的？

### ISSUE THREAD

**Issue by hefengzz** [copyliu/bililive_dm#90]
抱歉，以这种形式发起提问。。。实在是短见薄识看不懂C#的代码，大佬可否告知一下所用到的技术或者思路也行

**Comment by iRedmond** [comment]
topmost，直接在窗体属性上设置
不过你想问的或许不是这个？

**Comment by hefengzz** [comment]
我尝试用electron+vue来实现这个功能的时候，窗体可以置顶于其他程序之上，但无法置顶于全屏状态的游戏上，想知道是不是调用了系统驱动直接在屏幕上画出来的（java好像也不行）

**Comment by copyliu** [comment]
全屏状态需要借用提词板才能做到. 其他的一概都是假象
