### ISSUE TITLE
从十月份开始每次打开弹幕姬都弹出来获取颜色失败，是这个插件问题吗？

### ISSUE THREAD

**Issue by 1265578519** [copyliu/bililive_dm#94]
从十月份开始每次打开弹幕姬都弹出来获取颜色失败，是这个插件问题吗？

![image](https://user-images.githubusercontent.com/6442439/143291393-413452ef-e2d1-40db-af9d-50de6b729903.png)
![image](https://user-images.githubusercontent.com/6442439/143291515-887094eb-1e8b-434c-80b7-d4a062aa35a6.png)

有把弹幕颜色下面的自动更新去掉也不行

**Comment by copyliu** [comment]
請咨詢插件作者

**Comment by 1265578519** [comment]
差点找不到备份了，，，还好我有存档，我记得以前留了个issues发了zip。。怎么不见了
[AdminHelper.zip](https://github.com/copyliu/bililive_dm/files/7823385/AdminHelper.zip)
[LoginCenter.zip](https://github.com/copyliu/bililive_dm/files/7823386/LoginCenter.zip)
